### ISSUE TITLE
Themenübersicht

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Editor/BITS-hugo#9]
Ich würde die Themenübersicht lassen.
[https://bits-training.github.io/030-themenuebersicht/](url)
Dort kann man ggf. auch auf die linke Menüseite verweisen - da finden sich alle zurecht.
Was meint Ihr?

**Comment by andi-blafasl** [comment]
Ich würde die Seite entfernen. Ist redundant und muss manuell gepflegt werden. man sieht die Lektionen ja direkt in der Seitenleiste.

**Comment by BITS-Editor** [comment]
Ok. Hattest Du die Frage auf der Seite gestellt oder war das Werner? Wenn er es war, dann kann die Seite weg. Er ist ja offenbar Deiner Meinung. Wenn nein, würde ich seine Meinung noch gerne hören.

**Comment by andi-blafasl** [comment]
Ja, die Frage hat Werner auf die Seite geschriben. Ich lösche die Seite.

**Comment by BITS-Editor** [comment]
Danke!
